name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        name: Derive appropriate SHAs for base and head for `nx affected` commands
        with:
          main-branch-name: 'master'
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install --ignore-scripts --frozen-lockfile
        name: Install dependencies
      - run: yarn nx format:check
        name: Check style
      - run: yarn nx lint
        name: Lint
      - run: yarn test
        name: Run tests
      - run: yarn build
        name: Build
