name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
      - run: yarn build

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn nx format:check --all
